
// this is automatically generated from lws sources
// (using script ./make-cb-list)

static struct reason_list_s
{
	int reason;
        const char* what;
} reasons [] =
{
	{ LWS_CALLBACK_ESTABLISHED, "LWS_CALLBACK_ESTABLISHED" },
	{ LWS_CALLBACK_CLIENT_CONNECTION_ERROR, "LWS_CALLBACK_CLIENT_CONNECTION_ERROR" },
	{ LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH, "LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH" },
	{ LWS_CALLBACK_CLIENT_ESTABLISHED, "LWS_CALLBACK_CLIENT_ESTABLISHED" },
	{ LWS_CALLBACK_CLOSED, "LWS_CALLBACK_CLOSED" },
	{ LWS_CALLBACK_CLOSED_HTTP, "LWS_CALLBACK_CLOSED_HTTP" },
	{ LWS_CALLBACK_RECEIVE, "LWS_CALLBACK_RECEIVE" },
	{ LWS_CALLBACK_CLIENT_RECEIVE, "LWS_CALLBACK_CLIENT_RECEIVE" },
	{ LWS_CALLBACK_CLIENT_RECEIVE_PONG, "LWS_CALLBACK_CLIENT_RECEIVE_PONG" },
	{ LWS_CALLBACK_CLIENT_WRITEABLE, "LWS_CALLBACK_CLIENT_WRITEABLE" },
	{ LWS_CALLBACK_SERVER_WRITEABLE, "LWS_CALLBACK_SERVER_WRITEABLE" },
	{ LWS_CALLBACK_HTTP, "LWS_CALLBACK_HTTP" },
	{ LWS_CALLBACK_HTTP_FILE_COMPLETION, "LWS_CALLBACK_HTTP_FILE_COMPLETION" },
	{ LWS_CALLBACK_HTTP_WRITEABLE, "LWS_CALLBACK_HTTP_WRITEABLE" },
	{ LWS_CALLBACK_FILTER_NETWORK_CONNECTION, "LWS_CALLBACK_FILTER_NETWORK_CONNECTION" },
	{ LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION, "LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION" },
	{ LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS, "LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS" },
	{ LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS, "LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS" },
	{ LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION, "LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION" },
	{ LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER, "LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER" },
	{ LWS_CALLBACK_CONFIRM_EXTENSION_OKAY, "LWS_CALLBACK_CONFIRM_EXTENSION_OKAY" },
	{ LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED, "LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED" },
	{ LWS_CALLBACK_PROTOCOL_INIT, "LWS_CALLBACK_PROTOCOL_INIT" },
	{ LWS_CALLBACK_PROTOCOL_DESTROY, "LWS_CALLBACK_PROTOCOL_DESTROY" },
	{ LWS_CALLBACK_ADD_POLL_FD, "LWS_CALLBACK_ADD_POLL_FD" },
	{ LWS_CALLBACK_DEL_POLL_FD, "LWS_CALLBACK_DEL_POLL_FD" },
	{ LWS_CALLBACK_SET_MODE_POLL_FD, "LWS_CALLBACK_SET_MODE_POLL_FD" },
	{ LWS_CALLBACK_CLEAR_MODE_POLL_FD, "LWS_CALLBACK_CLEAR_MODE_POLL_FD" },
	{ -1, NULL }
};
