/* This file is automatically generated */

#ifndef __BINWARE_H__
#define __BINWARE_H__

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

typedef struct
{
	const char*		name;
	unsigned long		size;
	const unsigned char*	data;
} binware_s;

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

extern const binware_s binware_bin [];

#endif // __BINWARE_H__

